### ISSUE TITLE
hash_function option is required

### ISSUE THREAD

**Issue by lloydh6** [minhcasi/react-native-woocommerce#1]
I am trying to do a GET request via the WooCommerceApi and I get the following error;

hash_function option is required

Can you point me in the right direction please;

![screen shot 2017-06-05 at 19 48 12](https://cloud.githubusercontent.com/assets/8994487/26798346/fa081330-4a27-11e7-8e36-721abc851686.png)

**Comment by WilliamAnputra** [comment]
I still got this error, this is my package.json

  "dependencies": {
    "axios": "^0.18.0",
    "crypto": "^1.0.1",
    "moment": "^2.22.1",
    "oauth-1.0a": "^2.2.4",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-splash-screen": "3.0.6",
    "react-native-swiper": "^1.5.13",
    "react-navigation": "^2.0.0-rc.9",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.9.1",
    "redux-saga": "^0.16.0",
    "woocommerce": "^2.4.0"
  },

**Comment by rwschmitz** [comment]
Any luck with this?

**Comment by WilliamAnputra** [comment]
@rwschmitz  nope, i switched woocommerce to HTTPS and it works fine now.
